### ISSUE TITLE
How to reproduce your results? 

### ISSUE THREAD

**Issue by wjtan99** [jeff024/PALM#1]
Thanks for sharing your excellent work. 
I downloaded your checkpoint, and run runner.sh without training, and got the following results:

Evaluating SVHN
Evaluating places365
Evaluating LSUN
Evaluating iSUN
Evaluating dtd
 OOD detection method: SSD+
              FPR    AUROC  AUIN  
SVHN          93.04  47.28
places365     92.86  56.91
LSUN          84.43  56.97
iSUN          88.55  62.62
dtd           94.50  38.18
AVG           90.68  52.39
15.235417604446411

What did I do wrong?   Thanks a lot.

**Comment by jeff024** [comment]
Could you please double check that the save model is successfully loaded to GPU? Since the time used for evaluation only shouldn't be that long. I'm able to reproduce the results using the shared checkpoint model weights.

**Comment by wjtan99** [comment]
I retrained and retested, got the following results,  

23.542145490646362
Evaluating SVHN
Evaluating places365
Evaluating LSUN
Evaluating iSUN
Evaluating dtd
 OOD detection method: SSD+
              FPR    AUROC  AUIN  
SVHN           2.77  99.42
places365     64.68  83.01
LSUN          18.75  96.56
iSUN          35.20  92.63
dtd           36.60  92.43
AVG           31.60  92.81
1.4728095531463623

So it  is good.  Thank you.
