### ISSUE TITLE
can't replicate the results

### ISSUE THREAD

**Issue by DenizKizaroglu** [jeff024/PALM#3]
Hi, when I tried to use the runner.sh command (place the LSUN,iSUN,SVHN,dtd to the data) results that I have taken is below 

              FPR    AUROC   
SVHN           2.16  99.52
LSUN          10.13  97.81
iSUN          72.27  85.00
dtd           40.64  91.14
AVG           31.30  93.37

When I used the checkpoint, I got the results below 

                    FPR    AUROC   
SVHN           3.03  99.23
LSUN          10.58  97.70
iSUN          42.58  91.71
dtd           41.49  91.37
AVG           24.42  95.00

iSUN results are very different than expected. Can you help, replicating the results thanks

**Comment by jeff024** [comment]
sorry for the late reply. It seems that only the results of iSUN is a little bit different from our results. I would suggest that double check the dataset integrity or try out different random seeds. Cause the experiment results varies across different hardware platforms and versions of dependencies.
